# Generated by Django 2.2.9 on 2020-01-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
