# Generated by Django 2.2 on 2020-02-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200208_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField(default=0)),
                ('home', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
