# Generated by Django 2.2 on 2020-02-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200209_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['age']},
        ),
        migrations.AlterModelTable(
            name='student',
            table='students_info',
        ),
    ]
